AppBundle\Entity\DummyEntity:
  type: entity
  table: dummy_entity
  repositoryClass: AppBundle\Entity\DummyEntityRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  oneToMany:
    relations:
      targetEntity: AppBundle\Entity\DummyRelation
      mappedBy: dummy
  fields:
    title:
      type: string
    avatar:
      type: string
    sampleFile:
      type: string
    description:
      type: string
