<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DummyEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DummyEntityRepository extends EntityRepository
{
}